### ISSUE TITLE
NZ (New Zealand) Live Data Unavailable

### ISSUE THREAD

**Issue by leon-v** [electricitymap/electricitymap-contrib#3917]
Runtime logs showing
```
electricityMap.org recent parser errors for NZ
Last updated: Mon, 28 Mar 2022 20:02:18+0000
Yay, no recent errors.
```

However map showing no data:
https://app.electricitymap.org/zone/NZ

My Home Assistant started showing erroneous/low CO2 data from the API since 17 March 2022

Can anyone help identify the issue ?

**Comment by leon-v** [comment]
While testing, i was getting a number of issues (i believe because i'm using Python 3.10), but i was able to get a response that looked OK after adding:
```
import collections
collections.Callable = collections.abc.Callable
```
to NZ.py

Before this change, i was getting:
```

...

File "/Users/leonvalkenborg/Documents/electricitymap-contrib/parsers/NZ.py", line 24, in fetch
    soup = BeautifulSoup(response.text, 'html.parser')

.......


File "/Users/leonvalkenborg/Documents/electricitymap-contrib/.venv/lib/python3.10/site-packages/bs4/element.py", line 1615, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
AttributeError: module 'collections' has no attribute 'Callable'
```

**Comment by leon-v** [comment]
Created branch with above fix on forked repo.
Unsure is this fix is related the the problem at all, it may just be related to my enviroment.

https://github.com/leon-v/electricitymap-contrib/tree/leon-v/Fix-NZ-HTML-Parser-Error

**Comment by leon-v** [comment]
Installed the development environment on my Ubuntu box and had none of the issues above.

So none of that is the issue..

**Comment by jarek** [comment]
Per https://github.com/electricitymap/electricitymap-contrib/issues/3894#issuecomment-1076258550 , this might have been just because the source didn't have updated data.

electricitymap.org has just started showing live data now (looks 1-2 hours old), with generation data missing before

The ultimate source is https://www.transpower.co.nz/power-system-live-data and that currently reports "Updated: 29 Mar 2022 14:45" which appears to be 5 minutes ago for Auckland timezone.

If you try now, does it work?

Interesting that it might not work on Python 3.10... if you can confirm that, can you make a separate issue? or maybe it's an issue in BeautifulSoup and we might need to update the BeautifulSoup version we use?

**Comment by kruschk** [comment]
@jarek When executing `poetry run test`, the following warning is printed:

> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working

It sounds like BeautifulSoup will indeed need to be upgraded when upgrading to Python 3.10.

**Comment by madsnedergaard** [comment]
Data is looking fine and has been fine for at least last 24 hours, so closing this again :)
