### ISSUE TITLE
Wind layer is still broken

### ISSUE THREAD

**Issue by q--** [electricitymap/electricitymap-contrib#4124]
Still broken after merging #4121

On e.g. [GE?wind=true](https://app.electricitymap.org/zone/GE?wind=true)
> Error message: a.fromNow is not a function

Seen in both Firefox and Chrome on Desktop, including in private browsing.

**Comment by VIKTORVAV99** [comment]
Hopefully #4123 will fix that when it's merged.

**Comment by q--** [comment]
#4123 fixed it
